package integration.interfaces;

import domain.CatalogueItem;

import java.util.List;

/**
 * So that user of PU can search for a specific item by its item ID and get all available information (description, package type, units in a pack, cost, availability)
 */
public interface IStockService {

	/**
	 * So that user of PU can search for a specific item by its item ID and get all available information (description, package type, units in a pack, cost, availability). Returns an object of type catalogueItem.
	 * @param itemID
	 */
	CatalogueItem itemAvailability(String itemID);

	/**
	 * So that user of PU can search stock based on a keyword, returns a List containing objects of type catalogueItem.
	 * User will be able to see item ID, description, package type, units in a pack, cost.
	 * @param keyword
	 */
	List<CatalogueItem> searchStock(String keyword);

	/**
	 * So that when a customer is buying items in the stock, they become reserved so that others cannot buy those items.
	 * Returns a string for reservation ID
	 * Parameters are two arrays, one array for IDs of ordered items, a second array for quantity.
	 * @param itemID Array containing Item IDs of ordered items
	 * @param quantity Array containing quantity of ordered items
	 */
	String reserveItemsforPurchase(String[] itemID, int[] quantity);

	/**
	 * Confirms reserved items as sold, removing reserved items from stock on CA
	 * @param reservationID This is the ID generated by +reserveItemsforPurchase()
	 */
	String deductStock(String reservationID);

	/**
	 * Cancels reserved items, so they are available again for others to buy
	 * @param reservationID
	 */
	boolean cancelReservedItems(String reservationID);

	/**
	 * Returns a List of CatalogueItems which contains all information on all catalogue items
	 */
	List getCatalogue();

}